name: setup deps
description: setup the job with node, pnpm and project dependencies
runs:
  using: 'composite'
  steps:
    - run: |
        echo "rename use-node-version to node-version to avoid issues with vercel build"
        sed -i 's/use-node-version/node-version/g' .npmrc
      shell: bash
    - uses: pnpm/action-setup@v4
    - run: |
      echo "$(pnpm config get node-version)"
      echo "NODE_VERSION=$(pnpm config get node-version)" >> $GITHUB_ENV
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
      shell: bash
