name: setup deps
description: setup the job with node, pnpm and project dependencies
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - run: |
        echo "$(pnpm config get use-node-version)"
        echo "NODE_VERSION=$(pnpm config get use-node-version)" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
      shell: bash
