name: release
on:
  workflow_run:
    workflows: ['test']
    branches: [main]
    types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
      - run: npx turbo run release --filter=[HEAD^1]

  version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm build
      - uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: '🔖 Publish packages'
          title: '🔖 Publish packages'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
